Collections:
  - Name: GauCho
    Paper:
      URL: https://arxiv.org/pdf/2502.01565
      Title: 'GauCho: Gaussian Distributions with Cholesky Decomposition for Oriented Object Detection'
    Code:
      URL: https://github.com/jhlmarques/GauCho
    README: configs/gaucho/README.md

Models:
  - Name: gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota15_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav15/SOTA/gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.5 multi-scale
    Weights: checkpoint/gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.pth

  - Name: gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota15_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav15/SOTA/gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.5 multi-scale
    Weights: checkpoint/gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.pth

  - Name: gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota15_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav15/SOTA/gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.5 multi-scale
    Weights: checkpoint/gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota15_ms_rr_le90.pth

  - Name: gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/gaussian_fcos_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/gaussian_fcos_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/gaussian_fcos_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: oriented_rcnn_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/oriented_rcnn_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/oriented_rcnn_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: oriented_rcnn_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/oriented_rcnn_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/oriented_rcnn_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: oriented_rcnn_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/oriented_rcnn_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/oriented_rcnn_r152_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: roi_transformer_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/roi_transformer_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/roi_transformer_r50_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth

  - Name: roi_transformer_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90
    In Collection: GauCho
    Config: configs/gaucho/dotav1/SOTA/roi_transformer_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.py
    Metadata:
      Training Data: DOTAv1.0 multi-scale
    Weights: checkpoint/roi_transformer_r101_fpn_gaucho_probiou_1x_dota_ms_rr_le90.pth
